local screenmaster = require( "screenmaster.screenmaster" )

function init( self ) 
	msg.post( ".", "acquire_input_focus" )
end


function on_input( self, action_id, action )
	if action.pressed then
		if gui.pick_node( gui.get_node( "button" ), action.x, action.y ) then
			local messages = {}
			messages[ "levelB:/root" ] = { value = "A sends some arbitray data to B..." }
			
			msg.post( "main:/screenmaster" , "load", { level = "levelB", messages = messages } )
		end
	end
end
