local cnt = 0


function init( self )
	print( "Welcome to the game...!" )
	msg.post( ".", "loadLevel" )
end


function update( self, dt )
	cnt = cnt + 1
	if cnt > 100 then 
		pprint( "Main updating..." )
		cnt = 0
	end
end


function on_message( self, message_id, message, sender )
	if message_id == hash( "loadLevel" ) then
		msg.post( "screenmaster", "load", { level = "levelA" } )
	end
end


function on_input( self, action_id, action )
end

